import { useState } from "react"
import { Link } from "react-router-dom"
import { Plus, Search } from "lucide-react"
import StatusBadge from "../components/StatusBadge"
const employees = [{id:"E001",name:"Mike Jones",role:"Driver",status:"active",completion:100},{id:"E002",name:"Sarah Smith",role:"Driver",status:"onboarding",completion:60},{id:"E003",name:"David Brown",role:"Admin",status:"active",completion:100},{id:"E004",name:"Lisa Davis",role:"Driver",status:"onboarding",completion:30},{id:"E005",name:"Tom Wilson",role:"Driver",status:"terminated",completion:85}]
export default function EmployeesPage(){
  const [q,setQ]=useState("")
  const filtered = employees.filter(e => e.name.toLowerCase().includes(q.toLowerCase()))
  return <div><div className="flex items-center justify-between mb-6"><h1 className="text-2xl font-bold text-gray-900">Employees</h1><Link to="/employees/new" className="bg-[#1E3A5F] text-white px-4 py-2 rounded-lg text-sm font-semibold flex items-center gap-2"><Plus className="h-4 w-4"/>Add Employee</Link></div><div className="relative mb-6"><Search className="absolute left-3 top-2.5 h-4 w-4 text-gray-400"/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg text-sm" placeholder="Search employees..."/></div><div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden"><table className="w-full text-sm"><thead><tr className="border-b border-gray-200 bg-gray-50"><th className="text-left py-3 px-4 font-semibold text-gray-600">Name</th><th className="text-left py-3 px-4 font-semibold text-gray-600">Role</th><th className="text-left py-3 px-4 font-semibold text-gray-600">Status</th><th className="text-left py-3 px-4 font-semibold text-gray-600">Onboarding</th><th className="text-left py-3 px-4 font-semibold text-gray-600">Actions</th></tr></thead><tbody>{filtered.map(e=><tr key={e.id} className="border-b border-gray-100 hover:bg-gray-50"><td className="py-3 px-4 font-medium text-gray-900">{e.name}</td><td className="py-3 px-4 text-gray-600">{e.role}</td><td className="py-3 px-4"><StatusBadge status={e.status}/></td><td className="py-3 px-4"><div className="flex items-center gap-2"><div className="flex-1 h-2 bg-gray-200 rounded-full"><div className="h-2 bg-[#1E3A5F] rounded-full" style={{width:e.completion+"%"}}/></div><span className="text-xs text-gray-500">{e.completion}%</span></div></td><td className="py-3 px-4"><Link to={`/employees/${e.id}`} className="text-[#1E3A5F] text-sm font-medium hover:underline">View</Link></td></tr>)}</tbody></table></div></div>
}
