import { useState } from "react"
import { useParams, Link } from "react-router-dom"
import { ArrowLeft } from "lucide-react"
const content={safety:{title:"Safety & Compliance Fundamentals",sections:["DOT/FMCSA Overview","Personal Protective Equipment","Accident Prevention","Emergency Procedures"],quiz:[{q:"What does FMCSA stand for?",o:["Federal Motor Carrier Safety Administration","Freight Management & Cargo Safety Association","Fleet Management Compliance Standards Agency"],c:0},{q:"How often must a DOT physical be renewed?",o:["Every 6 months","Every 2 years","Every year"],c:1}]},operations:{title:"Daily Operations & Procedures",sections:["Pre-Trip Inspections","Hours of Service Logging","Route Planning","Load Securement"],quiz:[{q:"What is the maximum driving time per day under HOS rules?",o:["10 hours","11 hours","14 hours"],c:1},{q:"When should a pre-trip inspection be completed?",o:["At the end of each trip","Before each trip","Once a week"],c:1}]},policy:{title:"Company Policy & Culture",sections:["Code of Conduct","Attendance Policy","Reporting Procedures","Professional Standards"],quiz:[{q:"When should you report an accident?",o:["Within 24 hours","Immediately","By end of shift"],c:1},{q:"How many unexcused absences trigger a review?",o:["2","3","5"],c:1}]}}
export default function TrainingModulePage(){
  const {id}=useParams<{id:string}>(); const [quizMode,setQuizMode]=useState(false); const [score,setScore]=useState<number|null>(null)
  const mod = content[id as keyof typeof content] || content.safety
  const [answers,setAnswers]=useState<number[]>([])
  const submitQuiz=()=>{const s=mod.quiz.reduce((acc,q,i)=>acc+(answers[i]===q.c?1:0),0);setScore(Math.round(s/mod.quiz.length*100))}
  if(score!==null)return <div className="max-w-2xl mx-auto text-center py-12 bg-white rounded-xl shadow-sm border"><div className="w-20 h-20 rounded-full bg-green-100 flex items-center justify-center mx-auto mb-4"><span className="text-4xl text-green-600">{score>=70?"🎉":"📚"}</span></div><h2 className="text-2xl font-bold mb-2">{score>=70?"Passed!":"Keep Learning"}</h2><p className="text-4xl font-extrabold text-[#1E3A5F] mb-4">{score}%</p><p className="text-gray-500 mb-6">{score>=70?"Great job! You passed the module.":"Review the material and try again."}</p><Link to="/training" className="inline-block px-6 py-2 bg-[#1E3A5F] text-white rounded-lg">Back to Modules</Link></div>
  return <div className="max-w-4xl mx-auto"><Link to="/training" className="flex items-center gap-2 text-sm text-gray-500 hover:text-gray-700 mb-4"><ArrowLeft className="h-4 w-4"/>Back to Training</Link>  <h1 className="text-2xl font-bold mb-6">{mod.title}</h1>  {!quizMode?<><div className="bg-white rounded-xl p-6 shadow-sm border mb-6">{mod.sections.map((s,i)=><div key={i} className="mb-6"><h3 className="font-semibold text-lg mb-3">{i+1}. {s}</h3><p className="text-gray-600 text-sm leading-relaxed">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p></div>)}</div><button onClick={()=>setQuizMode(true)} className="px-6 py-3 bg-[#F59E0B] text-[#1E3A5F] rounded-lg font-semibold">Take Quiz</button></>  :<div className="bg-white rounded-xl p-6 shadow-sm border"><h2 className="font-semibold text-lg mb-6">Knowledge Check</h2>{mod.quiz.map((q,i)=><div key={i} className="mb-6"><p className="font-medium mb-3">{i+1}. {q.q}</p><div className="space-y-2">{q.o.map((opt,j)=><label key={j} className={`flex items-center gap-3 p-3 rounded-lg border cursor-pointer ${answers[i]===j?"border-[#1E3A5F] bg-blue-50":"border-gray-200"}`}><input type="radio" name={`q${i}`} onChange={()=>{const a=[...answers];a[i]=j;setAnswers(a)}} className="h-4 w-4 text-[#1E3A5F]"/><span className="text-sm">{opt}</span></label>)}</div></div>)}<button onClick={submitQuiz} className="px-6 py-3 bg-[#1E3A5F] text-white rounded-lg font-semibold">Submit Answers</button></div>}</div>
}
